Console.WriteLine("Enter the first number");
int a = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the second number");
int b = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the third number");
int c = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the fourth number");
int d = Convert.ToInt32(Console.ReadLine());
int Average = ((a + b + c + d)/4);
Console.WriteLine("The average of the numbers is :" +Average);
